# Generated by Django 3.1.6 on 2021-02-12 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.UUIDField(editable=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('editado', models.BooleanField(default=False, verbose_name='Editado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'operação',
                'verbose_name_plural': 'operações',
                'db_table': 'operacao',
            },
        ),
        migrations.CreateModel(
            name='InformacaoOperacionalOperacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade_responsavel', models.CharField(max_length=255, verbose_name='Unidade operacional responsável')),
                ('apoio_outras_unidades', models.BooleanField(verbose_name='Recebeu apoio de outras unidades')),
                ('unidade_apoiadora', models.CharField(blank=True, max_length=255, verbose_name='Unidade Apoiadora')),
                ('nome_comandante', models.CharField(max_length=255, verbose_name='Nome do Comandante')),
                ('rg_pm_comandante', models.CharField(max_length=10, verbose_name='RG PM do Comandante')),
                ('posto_comandante', models.CharField(choices=[('Cel', 'Coronel'), ('Ten Cel', 'Tenente Coronel'), ('Maj', 'Major'), ('Cap', 'Capitão'), ('1 Ten', 'Primeiro Tenente'), ('2 Ten', 'Segundo Tenente'), ('Subten', 'Subtenente'), ('1 Sgt', 'Primeiro Sargento'), ('2 Sgt', 'Segundo Sargento'), ('3 Sgt', 'Terceiro Sargento'), ('Cb', 'Cabo'), ('Sd', 'Soldado')], max_length=100, verbose_name='Posto|Graduação do Comandante')),
                ('tipo_operacao', models.CharField(choices=[('Pl', 'Planejada'), ('Em', 'Emergencial')], max_length=10, verbose_name='Tipo de operação')),
                ('tipo_de_acao_repressiva', models.CharField(choices=[('AREP I', 'AREP I'), ('AREP II', 'AREP II'), ('AREP III', 'AREP III'), ('AREP IV', 'AREP IV')], max_length=15, verbose_name='Tipo de ação repressiva')),
                ('objetivo_operacao', models.CharField(max_length=100, verbose_name='Objetivo da operação')),
                ('numero_policiais_mobilizados', models.PositiveIntegerField(verbose_name='Número de policiais mobilizados')),
                ('operacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.operacao')),
            ],
            options={
                'verbose_name': 'informção operacional da operação',
                'verbose_name_plural': 'informações operacionais da operação',
                'db_table': 'informacao_operacional_operacao',
            },
        ),
        migrations.CreateModel(
            name='InformacaoGeralOperacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('localidade', models.CharField(max_length=255, verbose_name='Localidade')),
                ('municipio', models.CharField(max_length=255, verbose_name='Município')),
                ('bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('endereco_referencia', models.CharField(max_length=255, verbose_name='Endereço de referência')),
                ('coordenadas_geo', models.CharField(blank=True, max_length=100, verbose_name='Referência geográfica')),
                ('batalhao_responsavel', models.CharField(max_length=255, verbose_name='Batalhão Responsável')),
                ('operacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.operacao')),
            ],
            options={
                'verbose_name': 'informação geral de operação',
                'verbose_name_plural': 'informações gerais de operação',
                'db_table': 'informacao_geral_operacao',
            },
        ),
    ]
