# Generated by Django 3.1.6 on 2021-02-12 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacao',
            name='identificador',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
