# Generated by Django 3.1.6 on 2021-03-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='secao_atual',
            field=models.PositiveIntegerField(default=1, verbose_name='Seção Atual'),
        ),
    ]
