# Generated by Django 3.1.6 on 2021-03-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_operacao_secao_atual'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='numero_aeronaves',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de aeronaves'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='numero_veiculos_blindados',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Número de veículos blindados'),
        ),
    ]
