# Generated by Django 3.1.6 on 2021-03-09 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_auto_20210304_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacao',
            old_name='numero_baixas_policiais',
            new_name='numero_mortes_policiais')
    ]
