# Generated by Django 3.1.6 on 2021-03-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_auto_20210309_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacao',
            name='numero_feridos_por_resistencia',
        ),
        migrations.AlterField(
            model_name='operacao',
            name='numero_mortes_policiais',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Número de mortes policiais'),
        ),
    ]
