# Generated by Django 3.1.6 on 2021-03-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_auto_20210309_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='descricao_analise_risco',
            field=models.TextField(blank=True, null=True, verbose_name='Análise de riscos e medidas de controles de danos colaterais das operações e de disparos de confrontos'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='justificativa_excepcionalidade_operacao',
            field=models.TextField(blank=True, null=True, verbose_name='Justificativa da excepcionalidade da operação'),
        ),
    ]
