# Generated by Django 3.1.6 on 2021-03-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_auto_20210310_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacao',
            name='observations',
            field=models.TextField(blank=True, null=True, verbose_name='Observações gerais'),
        ),
    ]
