# Generated by Django 3.1.6 on 2021-03-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_operacao_observations'),
        ('operations', '0006_auto_20210309_1909'),
    ]

    operations = [
    ]
