# Generated by Django 3.1.6 on 2021-03-12 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0010_historicaloperacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaloperacao',
            old_name='observations',
            new_name='observacoes_gerais',
        ),
        migrations.RenameField(
            model_name='operacao',
            old_name='observations',
            new_name='observacoes_gerais',
        ),
    ]
