# Generated by Django 3.1.6 on 2021-03-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0011_auto_20210312_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='nome_comandante_ocorrencia',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='posto_comandante_ocorrencia',
        ),
        migrations.RemoveField(
            model_name='historicaloperacao',
            name='rg_pm_comandante_ocorrencia',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='nome_comandante_ocorrencia',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='posto_comandante_ocorrencia',
        ),
        migrations.RemoveField(
            model_name='operacao',
            name='rg_pm_comandante_ocorrencia',
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='nome_condutor_ocorrencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do condutor da ocorrência'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='posto_condutor_ocorrencia',
            field=models.CharField(choices=[('Cel', 'Coronel'), ('Ten Cel', 'Tenente Coronel'), ('Maj', 'Major'), ('Cap', 'Capitão'), ('1 Ten', 'Primeiro Tenente'), ('2 Ten', 'Segundo Tenente'), ('Subten', 'Subtenente'), ('1 Sgt', 'Primeiro Sargento'), ('2 Sgt', 'Segundo Sargento'), ('3 Sgt', 'Terceiro Sargento'), ('Cb', 'Cabo'), ('Sd', 'Soldado')], max_length=100, null=True, verbose_name='Posto|Graduação do condutor da ocorrência'),
        ),
        migrations.AddField(
            model_name='historicaloperacao',
            name='rg_pm_condutor_ocorrencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RG PM do condutor da ocorrência'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='nome_condutor_ocorrencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome do condutor da ocorrência'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='posto_condutor_ocorrencia',
            field=models.CharField(choices=[('Cel', 'Coronel'), ('Ten Cel', 'Tenente Coronel'), ('Maj', 'Major'), ('Cap', 'Capitão'), ('1 Ten', 'Primeiro Tenente'), ('2 Ten', 'Segundo Tenente'), ('Subten', 'Subtenente'), ('1 Sgt', 'Primeiro Sargento'), ('2 Sgt', 'Segundo Sargento'), ('3 Sgt', 'Terceiro Sargento'), ('Cb', 'Cabo'), ('Sd', 'Soldado')], max_length=100, null=True, verbose_name='Posto|Graduação do condutor da ocorrência'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='rg_pm_condutor_ocorrencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='RG PM do condutor da ocorrência'),
        ),
    ]
