# Generated by Django 3.1.6 on 2021-04-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0013_auto_20210408_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloperacao',
            name='registro_anterior',
            field=models.BooleanField(default=False, verbose_name='Dado registrado fora do sistema'),
        ),
        migrations.AddField(
            model_name='operacao',
            name='registro_anterior',
            field=models.BooleanField(default=False, verbose_name='Dado registrado fora do sistema'),
        ),
    ]
